const PDFDocument = require('pdfkit');

/**
 * Generates a PDF report buffer.
 *
 * @param {Object} data
 * @param {string}   data.homeName
 * @param {string}   data.month           - e.g. "March 2025"
 * @param {number}   data.totalExpense
 * @param {number}   data.totalMeals
 * @param {number}   data.perMeal
 * @param {Array}    data.memberBreakdown  - [{ name, meals, share }]
 *
 * @returns {Promise<Buffer>}
 */
const generateReportPDF = (data) => {
  return new Promise((resolve, reject) => {
    const { homeName, month, totalExpense, totalMeals, perMeal, memberBreakdown = [] } = data;

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data',  chunk => chunks.push(chunk));
    doc.on('end',   ()    => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const PURPLE  = '#4F46E5';
    const DARK    = '#111827';
    const GRAY    = '#6B7280';
    const LIGHT   = '#F5F3FF';
    const WHITE   = '#FFFFFF';
    const ROW_ALT = '#F9FAFB';
    const W       = 495; // usable width (595 - 2*50)

    // ── Header bar ────────────────────────────────────
    doc.rect(0, 0, 595, 70).fill(PURPLE);
    doc.fillColor(WHITE).fontSize(22).font('Helvetica-Bold')
       .text('MealApp', 50, 20);
    doc.fontSize(11).font('Helvetica')
       .text('Monthly Expense Report', 50, 46);

    // ── Sub-header ────────────────────────────────────
    doc.fillColor(DARK).fontSize(13).font('Helvetica-Bold')
       .text(homeName, 50, 90);
    doc.fillColor(GRAY).fontSize(11).font('Helvetica')
       .text(`Period: ${month}`, 50, 108);

    // ── Divider ───────────────────────────────────────
    doc.moveTo(50, 130).lineTo(545, 130).strokeColor('#E5E7EB').lineWidth(1).stroke();

    // ── Summary cards (3 boxes) ───────────────────────
    const cardY  = 145;
    const cardW  = 148;
    const cardH  = 64;
    const gap    = 25;

    const cards = [
      { label: 'Total Expenses',  value: `৳${totalExpense.toFixed(2)}` },
      { label: 'Total Meals',     value: String(totalMeals)            },
      { label: 'Cost Per Meal',   value: `৳${perMeal.toFixed(2)}`      }
    ];

    cards.forEach((card, i) => {
      const x = 50 + i * (cardW + gap);
      doc.rect(x, cardY, cardW, cardH).fill(LIGHT).stroke();
      doc.fillColor(GRAY).fontSize(9).font('Helvetica')
         .text(card.label.toUpperCase(), x + 10, cardY + 10, { width: cardW - 20 });
      doc.fillColor(PURPLE).fontSize(18).font('Helvetica-Bold')
         .text(card.value, x + 10, cardY + 26, { width: cardW - 20 });
    });

    // ── Member Breakdown table ────────────────────────
    let y = cardY + cardH + 30;

    doc.fillColor(DARK).fontSize(13).font('Helvetica-Bold')
       .text('Member Breakdown', 50, y);
    y += 22;

    // Table header row
    doc.rect(50, y, W, 24).fill(PURPLE);
    doc.fillColor(WHITE).fontSize(10).font('Helvetica-Bold');
    doc.text('Member',       60,  y + 7, { width: 200 });
    doc.text('Meals',       260,  y + 7, { width: 100 });
    doc.text('Share (৳)',   370,  y + 7, { width: 120 });
    y += 24;

    if (memberBreakdown.length === 0) {
      doc.rect(50, y, W, 26).fill(ROW_ALT);
      doc.fillColor(GRAY).fontSize(10).font('Helvetica')
         .text('No meal data for this period.', 60, y + 8);
      y += 26;
    } else {
      memberBreakdown.forEach((m, i) => {
        const bg = i % 2 === 0 ? WHITE : ROW_ALT;
        doc.rect(50, y, W, 26).fill(bg);
        doc.fillColor(DARK).fontSize(10).font('Helvetica');
        doc.text(m.name,              60,  y + 8, { width: 190 });
        doc.text(String(m.meals),    260,  y + 8, { width: 100 });
        doc.text(m.share.toFixed(2), 370,  y + 8, { width: 120 });
        y += 26;
      });
    }

    // Bottom border of table
    doc.moveTo(50, y).lineTo(545, y).strokeColor('#E5E7EB').lineWidth(1).stroke();

    // ── Footer ────────────────────────────────────────
    const footerY = doc.page.height - 50;
    doc.moveTo(50, footerY - 10).lineTo(545, footerY - 10)
       .strokeColor('#E5E7EB').lineWidth(1).stroke();
    doc.fillColor(GRAY).fontSize(9).font('Helvetica')
       .text(
         `Generated by MealApp on ${new Date().toLocaleDateString('en-GB', { dateStyle: 'long' })}`,
         50, footerY, { align: 'center', width: W }
       );

    doc.end();
  });
};

module.exports = { generateReportPDF };